- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true
  become_user: root
  become_method: sudo

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
    state: present
  become: true

