- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true
  become_user: root
  become_method: sudo

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
    state: present
  become: true

- name: Ensure .zsh directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.zsh"
    state: directory
    mode: "0755"

- name: Add zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-autosuggestions"
    force: yes

- name: Add zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-syntax-highlighting"
    force: yes
