[tools]
uv = "latest"
prek = "latest"
shellcheck = "latest"
node = "lts"

[settings]
experimental = true

[env]
_.file = '.env'         # for sensitive data
UV_LINK_MODE = "copy"
_.python.venv = ".venv"

[hooks]
enter = "bash ./scripts/enter_project.sh"
