[tools]
markdownlint-cli2 = "latest"
node = "lts"
prek = "latest"
shellcheck = "latest"
uv = "latest"

[settings]
experimental = true

[settings.aqua]
github_attestations = false

[env]
_.file = '.env'       # for sensitive data
UV_LINK_MODE = "copy"

[hooks]
enter = "bash ./scripts/enter_project.sh"

[tasks.ansible_lint]
run = "ANSIBLE_CONFIG=ansible/ansible.cfg ansible-lint ansible/"
description = "Run ansible lint"

[tasks.docs]
run = "zensical serve"
description = "Serve the documentation locally"
