[tools]
starship = "latest"
zoxide = "latest"
fzf = "latest"
bat = "latest"
bottom = "latest"
eza = "latest"
shfmt = "latest"
shellcheck = "latest"
jq = "latest"
jqp = "latest"
direnv = "latest"
ripgrep = "latest"
