[tools]
starship = "latest"
kubectl = "latest"
terraform = "latest"
zoxide = "latest"
fzf = "latest"
bat = "latest"
dust = "latest"
fastfetch = "latest"
dive = "latest"
btop = "latest"
eza = "latest"
yt-dlp = "latest"
shfmt = "latest"
shellcheck = "latest"
jq = "latest"
jqp = "latest"
podman = "latest"
flux2 = "latest"
k9s = "latest"
uv = "latest"
# pnpm = "latest"
