data:
  # variant: workstation  # default value, can be overridden by env var (export CHEZMOI_DATA_variant=wsl)
  variants:
    workstation:
      install:
        starship: true # ansible
        tmux: true # ansible
        zsh_plugin: true # ansible
        kubectl: true # mise
        terraform: true # mise
        zoxide: true # mise
        fzf: true # mise
        bat: true # mise
        dust: true # mise
        fastfetch: true # mise
        dive: true # mise
        btop: true # mise
        eza: true # mise
        ytdlp: true # mise
        shfmt: true # mise
        shellcheck: true # mise
        jq: true # mise
        jqp: true # mise
        podman: true # mise
        flux2: true # mise
        k9s: true # mise
        vault: true # mise
        direnv: true # mise
        ripgrep: true # mise
        lazydocker: true # mise
        uv: true # mise
        pnpm: false # mise
    wsl:
      install:
        starship: true # ansible
        tmux: true # ansible
        zsh_plugin: true # ansible
        kubectl: true # mise
        terraform: true # mise
        zoxide: true # mise
        fzf: true # mise
        bat: true # mise
        dust: true # mise
        fastfetch: true # mise
        dive: true # mise
        btop: true # mise
        eza: true # mise
        ytdlp: false # mise
        shfmt: true # mise
        shellcheck: true # mise
        jq: true # mise
        jqp: true # mise
        podman: false # mise
        flux2: true # mise
        k9s: true # mise
        vault: true # mise
        direnv: true # mise
        ripgrep: true # mise
        lazydocker: true # mise
        uv: true # mise
        pnpm: false # mise
    devcontainer:
      install:
        starship: true # mise
        tmux: true # ansible
        zsh_plugin: false # ansible
        kubectl: true # mise
        terraform: true # mise
        zoxide: true # mise
        fzf: true # mise
        bat: true # mise
        dust: false # mise
        fastfetch: false # mise
        dive: false # mise
        btop: false # mise
        eza: true # mise
        ytdlp: false # mise
        shfmt: true # mise
        shellcheck: true # mise
        jq: false # mise
        jqp: false # mise
        podman: false # mise
        flux2: false # mise
        k9s: true # mise
        vault: false # mise
        direnv: true # mise
        ripgrep: true # mise
        lazydocker: false # mise
        uv: false # mise
        pnpm: false # mise
