data:
  # variant: workstation  # default value, can be overridden by env var (export CHEZMOI_DATA_variant=wsl)
  variants:
    workstation:
      install:
        starship: true # ansible
        tmux: true # ansible
        zsh_plugin: true # ansible
        kubectl: true # mise
        terraform: true # mise
        zoxide: true # mise
        fzf: true # mise
        bat: true # mise
        dust: true # mise
        pnpm: false # mise
        uv: true # mise
    wsl:
      install:
        starship: true # ansible
        tmux: true # ansible
        zsh_plugin: true # ansible
        kubectl: true # mise
        terraform: true # mise
        zoxide: true # mise
        fzf: true # mise
        bat: true # mise
        dust: true # mise
        pnpm: false # mise
        uv: true # mise
    devcontainer:
      install:
        starship: true # mise
        tmux: true # ansible
        zsh_plugin: false # ansible
        kubectl: false # mise
        terraform: false # mise
        zoxide: true # mise
        fzf: true # mise
        bat: true # mise
        dust: true # mise
        pnpm: false # mise
        uv: false # mise
