data:
  # variant: workstation  # default value, can be overridden by env var (export CHEZMOI_DATA_variant=wsl)
  variants:
    workstation:
      install:
        starship: true
        kubectl: true
        pnpm: false
        uv: true
    wsl:
      install:
        starship: true
        kubectl: true
        pnpm: false
        uv: true
    devcontainer:
      install:
        starship: true
        kubectl: false
        pnpm: false
        uv: false
