#!/usr/bin/zsh

# Load completion system
autoload -Uz compinit
compinit

# Option configuration
HISTSIZE=2000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt APPENDHISTORY          # Append history lines to the history file, rather than overwriting it.
setopt SHAREHISTORY           # Share history between all sessions.
setopt HIST_IGNORE_SPACE      # Ignore commands that start with a space.
setopt HIST_IGNORE_ALL_DUPS   # Remove all previous duplicates of a command from the history list when added.
setopt HIST_SAVE_NO_DUPS      # Don't write duplicate entries in the history file.
setopt HIST_IGNORE_DUPS       # Don't record an entry that was just recorded again.
setopt HIST_FIND_NO_DUPS      # Do not display a line previously found.
setopt BANG_HIST              # Treat the '!' character specially during expansion.
setopt INC_APPEND_HISTORY     # Write to the history file immediately, not when the shell exits.
setopt HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history.

# Completion styling
zstyle ':completion:*' menu no                 # Disable menu-based selection during tab completion.
zstyle ':completion:*' accept-exact '*(N)'     # Automatically accept exact matches when completing.
zstyle ':completion:*' use-cache on            # Enable caching for faster completion results.
zstyle ':completion:*' cache-path ~/.zsh/cache # Define the location to store the completion cache.

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Keybindings
bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
bindkey '^[[C' forward-char
bindkey '^[[D' backward-char
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^H" backward-kill-word
bindkey "^?" backward-delete-char

# Aliases
alias ls='ls --color'
alias py="python3"
alias pya="source ./.venv/bin/activate"

# set color
export COLORTERM=truecolor

# Manage paths
export PATH="$HOME/.local/share/mise/shims:$HOME/.local/bin:$PATH"

# mise setup
eval "$(mise activate zsh)"

# starship setup
eval "$(starship init zsh)"

# kubectl setup
source <(kubectl completion zsh)
alias k="kubectl"

# terraform setup
alias tf="terraform"

# zoxide setup
eval "$(zoxide init zsh --cmd cd)"

# fzf setup
source <(fzf --zsh)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS=" \
--color=fg:15,bg:0,hl:14 \
--color=fg+:15,bg+:0,hl+:12 \
--color=info:10,prompt:9,pointer:13 \
--color=marker:10,spinner:13,header:6 \
--multi"

# bat setup
if ! mise which bat &>/dev/null; then
    bat cache --build
fi
alias cat="bat"

# eza setup
alias ls="eza -al --icons --group-directories-first --git --time-style=relative"
alias tree="eza --tree --icons --git-ignore -a"

# flux2 setup
source <(flux completion zsh)

# vault setup
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C vault vault

# lazydocker setup
alias ld=lazydocker

# uv setup
eval "$(uv generate-shell-completion zsh)"
eval "$(uvx --generate-shell-completion zsh)"

# Plugins
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=true
ZSH_AUTOSUGGEST_MANUAL_REBIND=true
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#7f849c"

# Autosuggestions
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
# Syntax highlighting (always last)
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
