- name: Check if Tmux is installed
  ansible.builtin.shell: tmux -V
  register: tmux_check
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Install Tmux if not installed
  ansible.builtin.package:
    name: tmux
    state: present
  when: tmux_check.rc != 0
  become: true
