- name: Check if Tmux is installed
  ansible.builtin.command: tmux -V
  register: tmux_check
  changed_when: false
  failed_when: tmux_check.rc != 0

- name: Install Tmux if not installed
  ansible.builtin.package:
    name: tmux
    state: present
  when: tmux_check.failed
  become: true

# - name: Copy Tmux configuration file
#   ansible.builtin.copy:
#     src: files/.tmux.conf
#     dest: "{{ ansible_env.HOME }}/.tmux.conf"
#     owner: "{{ ansible_env.USER }}"
#     group: "{{ ansible_env.USER }}"
#     mode: '0644'
