- name: Debug Git variables
  ansible.builtin.debug:
    msg:
      - "Git User Name: {{ git_user_name }}"
      - "Git User Email: {{ git_user_email }}"

- name: Ensure Git is installed
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Configure Git username
  community.general.git_config:
    scope: global
    name: user.name
    value: "{{ git_user_name }}"
  when: git_user_name is defined
  become: false

- name: Configure Git email
  community.general.git_config:
    scope: global
    name: user.email
    value: "{{ git_user_email }}"
  when: git_user_email is defined
  become: false
